---
- name: Uninstall icam agents 
  hosts: all
  vars_files:
    - vars/commonvars.yml
    - vars/icamvars.yml
 
  tasks:
 
# tasks file for uninstall-all

  - name:  Test if "{{ install_dir }}" directory exists
    stat:
      path:  "{{ install_dir }}"
    register: itmdir

  - name: ending the play if icam dir does not exist
    meta: end_play
    when:
      - itmdir.stat.exists == false

  - block:

    - name: "Uninstall ITM from {{install_dir}}"
      shell: "echo y | {{install_dir}}/bin/smai-agent.sh uninstall_all"
      ignore_errors: yes

  - name: "Delete the dir: {{install_dir}}"
    file:
      path: "{{install_dir}}"
      state: absent
      force: yes
    ignore_errors: yes


